name: starter-react-vite-test

services:
  app-local:
    # build the Docker image named "starter-react-vite" from the local Dockerfile
    image: starter-react-vite
    build:
      context: .
      dockerfile: Dockerfile
      # Optional: specify a custom env file for the build
      # args:
      #   ENV_FILE: .env.production
    ports:
      - "8080:80"
  app-prod:
    image: tiogars/starter-react-vite:latest
    ports:
      - "8081:80"